[[plugins]]
repo = 'itchyny/lightline.vim' " ステータスラインの表示内容強化

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'tacahiroy/ctrlp-funky'

[[plugins]]
repo = 'suy/vim-ctrlp-commandline'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'kana/vim-submode'
